#!/bin/bash

#SBATCH --time=96:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=1024M   # memory per CPU core
#SBATCH -J "blast"   # job name
#SBATCH --mail-user=mgjijon@byu.edu   # email address
#SBATCH --mail-type=FAIL


# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE

source ~/.bashrc
conda activate blast

species=$1
gene=$2
query="${gene}_query.fasta"
genome="../genomes/${species}_genome.fasta"
output="../b_results/${species}_${gene}.out"

tblastn -db $genome -query $query  -out $output -outfmt 7
